### ISSUE TITLE
Se connecter *à OSM*

### ISSUE THREAD

**Issue by CharlesNepote** [DoFabien/OsmGo#1]
Tout d'abord bravo pour cette app !

Un détail : dans le menu "OSM Go!", l'option "Se connecter" n'est pas claire. Se connecter à quoi ? Il faut un compte pour cette appli ? me suis-je demandé.

Je suggère de préciser "Se connecter à OpenStreetMap" et/ou de l'indiquer dans la fenêtre de connexion : "Email ou nom d'utilisateur OpenStreetMap".

**Comment by DoFabien** [comment]
Bonjour et merci du retour !
J'ai suivi à la lettre vos suggestions. 1f40c37643e7e21317a91b13058203e14dc489ea

Une nouvelle version sera disponible certainement ce week end.
