### ISSUE TITLE
Supporting OSM Notes

### ISSUE THREAD

**Issue by Kalepom** [DoFabien/OsmGo#10]
Bonjour, 
Lors des observations terrain, on peut avoir des remarques à ajouter qui ne passent pas par l'ajout d'un POI, ou parfois on ne trouve pas le bon POI à ajouter. Dans ces cas là, il serait utile de pouvoir ajouter une Note de carte via l'application.

**Comment by rouelibre1** [comment]
Je suis d'accord que ce serait vraiment super d'ajouter la possibilité de laisser une note. Si en plus l'utilisateur pouvait y joindre une photo (comme c'est le cas sur StreetComplete) ce serait absolument parfait.

**Comment by Binnette** [comment]
Closing as duplicate to #106
