### ISSUE TITLE
Nom d'affichage

### ISSUE THREAD

**Issue by Kalepom** [DoFabien/OsmGo#11]
Bonjour, 

Dans l'en-tête d'un POI, en nom d'utilisateur de la dernière personne ayant modifié l'élément, je vois parfois "Moi-même", parfois mon pseudo OSM et, depuis récemment, parfois mon adresse email. 
Est-ce un affichage normal ? Merci 

![screenshot_20181024-182700](https://user-images.githubusercontent.com/12937457/47513518-b6411e80-d87e-11e8-94b7-5b84806a6ff5.png)
![screenshot_20181025-174719](https://user-images.githubusercontent.com/12937457/47513519-b6411e80-d87e-11e8-9bb4-50bd8e69450a.png)
![img_20181025_175543_759](https://user-images.githubusercontent.com/12937457/47513789-48492700-d87f-11e8-9ddb-b80d32e4cc68.jpg)

**Comment by DoFabien** [comment]
Bonjour,
Le comportement d'afficher l'email n'était pas normal. Ca sera corrigé dans la prochaine version (la 0.6.0).

Tant que l'on a pas envoyé les données à OSM, dans le cas d'une modification ce sont  les méta données de la modification précédente qui sont affichées. 
Dans le cas ou c'est une création, on a une version 0 et l'auteur est "Moi même", car il est possible de créer un objet alors que nous ne sommes pas authentifié.
