### ISSUE TITLE
Add more custom imagery & editor-layer-index support

### ISSUE THREAD

**Issue by l-longour** [DoFabien/OsmGo#110]
### Expected behavior

To be allowed to have access to an imagery adapted to the mapping area by proposing some imageries according to the position by using https://osmlab.github.io/editor-layer-index/ . Have the possibility to add a TMS manually (as it exists on Vespucci) Maybe also Maxar Premium ? (very useful in many countries)

### Actual behavior

Three imageries available:

- IGN Ortho
- Satellite Mapbox
- Bing Maps

**Comment by Binnette** [comment]
We should first address this issue #111

**Comment by Binnette** [comment]
Fixed in 652ef0a5f8950d26b7e9676a5d1540d67db7e7b0
