### ISSUE TITLE
Should we drop the deprecated Mapbox GL JS ?

### ISSUE THREAD

**Issue by Binnette** [DoFabien/OsmGo#111]
Hi @DoFabien, it seems that Mapbox GL JS 1 is deprecated and version 2 do not have an opensource license and need a Mapbox account, token and have to pay after a certain amount of maps displayed.

I read this article: https://www.geoapify.com/mapbox-gl-new-license-and-6-free-alternatives

Given this article, if we want to drop Mapbox GL JS, our easiest option in to use maplibre-gl version 1 that is fully compatible with Mapbox GL JS 1.

Or we can also choose to use other alternatives described in the article if we need others features not provided by maplibre-gl

What do you think?

**Comment by DoFabien** [comment]
Hi, 
Yes, we should use Maplibre to replace Mapbox 1.x.
For the moment the 2 versions are almost similar, the change should be easy.

We use the Mapbox vector tiles as base map. Maybe we could use Maptiller's, I don't know.
