### ISSUE TITLE
Installation fails: unable to resolve dependency tree

### ISSUE THREAD

**Issue by dotcs** [DoFabien/OsmGo#114]
When trying to install the project with `npm install`, the routine fails with the error "unable to resolve dependency tree".
The `package.json` does not mention a supported node.js version, so I assume node v16 should be fine? Can this be confirmed by someone?

Maybe a `package.lock` file could help here if this conflict has been resolved somehow by the product team.

```console
$ npm install
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: osm_go@1.5.0
npm ERR! Found: zone.js@0.11.5
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.11.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.1.6" from the root project
npm ERR!   peer @angular/core@"10.2.5" from @angular/animations@10.2.5
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"^10.1.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/dotcs/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dotcs/.npm/_logs/2022-06-14T12_45_01_175Z-debug-0.log
```

```console
$ node --version
v16.14.2
$ npm --version
8.5.0
```

**Comment by Binnette** [comment]
Hi @dotcs, can you please go on branch develop and follow the instructions of the README (take the README of branch develop)

Normally it should work 👍

**Comment by dotcs** [comment]
Thanks for the quick reply, @Binnette. Indeed switching to the `develop` branch fixed the problem. 👍
But nevertheless, the installation throws a couple of warnings that are related to the used node.js and npm versions:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1200.5',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@12.0.5',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
```

Not sure if this is something a maintainer should have a look into.

And still I'm wondering if there is a reason to not use a `package.lock` file. Without this file it's not guaranteed that all devs work with the same versions which might lead to works-(not-)on-my-machine issues. [See docs](https://nodejs.dev/learn/the-package-lock-json-file) for details.

**Comment by Binnette** [comment]
I just added package.json in develop branch and add an info about required NodeJs version in the file contributing.md

Thank you for reporting this issue 👍 

Note: you can ignore this warnings. Or move to NodeJs 14.
