### ISSUE TITLE
Several aerial imageries do not work

### ISSUE THREAD

**Issue by JVillafruela** [DoFabien/OsmGo#118]
When testing the new aerial imagery menu in the develop branch (https://github.com/DoFabien/OsmGo/commit/a8e4137dc632079c108b113274280ae692237681) I noticed that several imageries do not show up. For example :

- ESRI Clarity : error 404 
- OSM B&W : CORS error

The CORS error (shown in Firefox dev console) is :

_Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://tiles.wmflabs.org/bw-mapnik/18/135232/94111.png. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 200._

I've also tested with Chrome on my smartphone, same results.

**Comment by Binnette** [comment]
Hi @JVillafruela, It is not an issue with Osm Go! It is an issue with ESRI Clarity and Mapnik Black & White.

So I will simply remove them from the list of available imagery.

Note: there is not yet a workaround in MapLibre GL (fork of Mapbox GL): mapbox/mapbox-gl-js/issues/6359

I also made a PR in osmlab/editor-layer-index/pull/1540 to add a property "support_cors" to easily identify tile servers that do not allow CORS.

Note that OSM Mapnik Black & White is no longer working/supported. So I will probably made a PR to remove it from osmlab/editor-layer-index

**Comment by Binnette** [comment]
Fixed in branch develop by removing not working imagery.

TY @JVillafruela for reporting the issue 👍

**Comment by Binnette** [comment]
FIY, I created a PR to remove Mapnik Black and white from editor-layer-index: osmlab/editor-layer-index/pull/1541

The tile server is working but return a default tile:
![image](https://user-images.githubusercontent.com/6597721/174021399-695e2937-2601-4d26-a87f-3ed1f7f1e8b1.png)
