### ISSUE TITLE
highway=street_lamp

### ISSUE THREAD

**Issue by bmallet** [DoFabien/OsmGo#12]
En tout premier lieu, merci pour cette app si pratique pour contribuer en ballade urbaine.
Serait-il possible d'ajouter :
highway=street_lamp
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp
Mais comme je lis que tu envisages "une petite interface pour simplifier l'ajout de tags et de presets", ce ne sera probablement pas nécessaire en dur dans l'app.

**Comment by DoFabien** [comment]
J'ai ajouté les clés de type "highway" dans l'app et donc, les lampadaires.
Pour ne pas surcharger la carte, certains ways ne seront pas affichés (les routes en faite). [La liste est disponible ici   ](https://github.com/DoFabien/OsmGo/blob/f1c5001ef3d944f2661bb03f56899595c29e6265/src/assets/tags/tags.json#L4178)

Du coup on a également les feux tricolores, les passages piétons, etc... Par contre, ceux ci devraient appartenir à un tronçon de route ce qui n'est pour l'instant impossible a faire directement dans l'application. 
A l'ajout d'un de ces tag il y aura donc une valeur par défaut "fixme".

Je vais tester cette version dans les rues avant de la déployer ce soir si je ne vois pas de gros bugs
