### ISSUE TITLE
POEditor links

### ISSUE THREAD

**Issue by Binnette** [DoFabien/OsmGo#122]
Hi @DoFabien, can you please create those links in POEditor:

1. Link "Chinese" to file zh-CN.json
2. Link "Chinese (TW)" to file zh-TW.json

Thanks 🙏

**Comment by DoFabien** [comment]
It's done.
Sorry for the latency... 
I was quite busy these last days. 
I hope to have some time to work on Osm Go next week.
Thanks a lot for your time

**Comment by Binnette** [comment]
Hi @DoFabien, don't worry and don't bother you 😇

I am really glad you can still find a little bit of time to work on OsmGo 👌

We are volunteers. So nobody can put pressure on us 😋
