### ISSUE TITLE
Problème affichage

### ISSUE THREAD

**Issue by ciseur68** [DoFabien/OsmGo#15]
Bonjour, depuis peu, j'ai un bug d'affichage sur mon Samsung Galaxy A6 : https://image.noelshack.com/fichiers/2019/18/2/1556641196-screenshot-20190430-180656-osm-go.jpg

**Comment by Binnette** [comment]
Hello, j'ai constaté le même bug en ayant lancé la version web (de debug). Au premier chargement de l'écran, la carte était tout petite. J'ai redimensionné mon navigateur et le problème a disparu. Sauf que toi, tu es sur smartphone, donc impossible de redimensionner la fenêtre.

Je pense que le bug vient du calcul de la taille de l'écran. Je pense que OsmGo calcul la taille de l'écran avant même que l'application ne soit affichée. Il faudrait modifier le code pour appeler la fonctionne de calcul de la taille de l'écran après que l'appli soit chargée.

**Comment by DoFabien** [comment]
Bonjour,
En fait ce bug vient de Mapbox GL JS qui, parfois,  à du mal a reconnaître le redimensionnement de la carte. 
Ce bug avait été corrigé il y a quelques mois mais semble revenu dans la dernière version.
Je regarde si je peux réparer ça rapidement

**Comment by DoFabien** [comment]
La version 0.7.3 devrait corriger le problème.
Néanmoins, je ne suis pas arrivé à reproduire le bug ... Ce serait donc bien de me confirmer, ou pas, cette correction

**Comment by Binnette** [comment]
Je viens de tester au avant ton commit : 
![image](https://user-images.githubusercontent.com/6597721/57235668-aff8df80-7023-11e9-9fd4-013a28111bbb.png)

Je reproduis bien le problème sous Ubuntu / Firefox

**Comment by Binnette** [comment]
Je viens de tester après ton commit. Pour moi le problème est corrigé sur la version web (testé avec Ubuntu/Firefox). Effectivement avant ton commit la carte est chargé toute petite et le reste tant que je ne redimensionne pas la fenêtre. Par contre, après ton commit, la carte se charge toute petite également, puis après 1 seconde, la carte est redimensionnée automatiquement et prends toute la place de ma fenêtre Firefox.

A tester sur téléphone, mais sur la version web, ça le fait.

**Comment by ciseur68** [comment]
Problème résolu sur Android !
