### ISSUE TITLE
Doublons non supprimables

### ISSUE THREAD

**Issue by ciseur68** [DoFabien/OsmGo#16]
Bonjour,
Suite à un édit, toutes mes modifications ont été comptées en double. Lors de l'envoi, bug sur la moitié puisque la version de l'objet à changé.
Depuis je n'arrive pas à supprimer ces modifs en allant dans Envoyer et Supprimer, il ne se passe rien avec le bouton confirmer.
Ainsi à chaque subit je suis obligé de les renvoyer, avec un bug de version

**Comment by DoFabien** [comment]
Bonjour, merci pour ton retour ! 
Je viens de pousser une petite mise à jour qui peut, éventuellement, corrigé ce problème, mais je n'y crois pas trop...
Je n'ai jamais vu ce comportement là, j'ai un peu tout essayé pour le reproduire ce matin, en vain.
Pourrais tu me dire si la version 0.8.1 corrige ce soucis ?

Sinon, il faudra supprimer les données et le cache depuis les paramètres Android : Application/ Osm Go !/ Stockage

Si la création de doublons se reproduit, pourrais tu m'en informer et me décrire dans quel contexte ceci c'est produit ?

Merci d'avance
