### ISSUE TITLE
Lowercase

### ISSUE THREAD

**Issue by Kalepom** [DoFabien/OsmGo#17]
Bonjour, 
Lors de l'ajout d'un tag, le clavier passe automatiquement en majuscule pour la 1re lettre. Or on vient de m'alerter que les tags étaient sensible à la casse et qu'ils pouvaient ne pas être références s'ils ne sont pas en minuscule.
Est-il possible de forcer le clavier en minuscule lors de la saisie et l'ajout de tags ?
Merci

**Comment by DoFabien** [comment]
Bonjour,
Oui les tags sont sensible à la casse. Je pensais d'ailleurs que toutes les clés devaient être en minuscule, j'avais donc intégré la conversion en minuscule pour tous les tags... Mais on m'a vite tapé sur les doigts... Certains tags, comme par exemple "school:FR" contient des majuscules. Du coup j'ai bien sûr retiré cette fonction...

Bref, ici ce n'est pas ce problème. J'ai testé avec 2 téléphones, avec Gboard, le clavier par défaut d'Android, il n'y a pas de problème, la première lettre est en minuscule par défaut, et il prend bien en compte la propriété [autocapitalize](https://developer.mozilla.org/fr/docs/Web/HTML/Attributs_universels/autocapitalize)
Par contre, avec le clavier SwiftKey, on a en effet toujours une majuscule à chaque début de phrase.. Mais là ça vient vraiment du paramètre du clavier

Quel clavier utilises tu ?

**Comment by Kalepom** [comment]
Merci de ton retour.
Je comprend bien. Effectivement, j'utilise SwiftKey. Je vais essayer de repasser à GBoard pour utiliser OSM Go !

Lucas Lechat
lucaslechat@outlook.com
06 72 69 77 53

________________________________

**Comment by DoFabien** [comment]
Sinon il est possible de désactiver [ l'autocap de swifkey ](https://support.swiftkey.com/hc/en-us/articles/201468481-How-do-I-turn-off-Auto-Capitalize-)

Pour info, il y a des chances que l'ajout de nouveaux tags évolue pour être un peu plus efficace et ergonomique. Je pense que ce sera le prochain petit chantier, sans doute à partir de la rentrée. D'ailleurs si tu as des propositions, elles sont les bienvenues !
