### ISSUE TITLE
Fond de carte OSM reste blanc

### ISSUE THREAD

**Issue by kroko83** [DoFabien/OsmGo#18]
Bonjour,

J'ai l'appli depuis 1 semaine et ça marchait nickel.
Depuis qq jours, je n'ai plus que le fond de carte OrthoIGN qui fonctionne. Les deux autres (OSM et Mapbox satellite) restent désespérément vides (=fond blanc).
J'ai mis à jour sur le Play Store (v0.9.2 Build 902) mais c'est toujours pareil.

Je n'ai pas de souci avec mes autres applis pour accéder à OSM : (Locus map, etc.)
Est-ce un pb de configuration de mon côté ?

PS : il y a peut-être un lien avec l'issue #15 mais je c'est pas sûr

**Comment by DoFabien** [comment]
Bonjour, merci de ton retour.
Je viens tout juste de me rendre compte de ce problème en voulant ajouter des commerces... 
J'essaye de fixer rapidement, ça vient certainement des flux Mapbox.

**Comment by DoFabien** [comment]
Ca venait de la clé d'API de Mapbox qui avait changé... Peut être dû au changement de mode de tarification de Mapbox. J’espère que ça ne va pas se reproduire.
A la rentrée, j'essayerais d’intégrer un paramètre pour utiliser les tuiles de Maptiler, au cas où...

C'est donc corrigé sur la nouvelle version (0.9.3), qui ne devrait pas tarder à arriver sur le Playstore ( l'apk est aussi disponible dans [realease](https://github.com/DoFabien/OsmGo/releases/tag/0.9.3)

**Comment by kroko83** [comment]
J'ai mis à jour via le Play Store et ça remarche.
Super réactif. Merci :)

Serait-il possible de fournir l'accès à d'autres serveurs de tuiles  ?
L'idéal serai un fichiers de conf où on indique l'adresse des serveurs dispo (appelé providers.xml sous Locus)

**Comment by DoFabien** [comment]
J'y pense,
C'est un chantier que j'ai commencé, avec l'ajout de nouvelles langues.
Pour chaque pays il devrait y avoir des sources différentes (eg: l'ign ne
couvre que la France...) .
A terme je souhaite que les utilisateurs puisse personnaliser les
tags/presets / valeurs par défaut, et les fonds de cartes, de façon assez
simple.

Par contre je ne pourrais pas reprendre ce travail avant septembre

--
Fabien

**Comment by kroko83** [comment]
OK, c'est clair que ça améliorerait l'utilisation.
Pour l'IGN, ça serait top mais ça voudrait dire un abonnement supplémentaire j'imagine.

Autre question : pourquoi tous les tags ne sont pas dispo (et les nodes associés non visibles) sur la carte ? Par exemple barrier=cycle_barrier et information=guidepost.
Initialement je pensais que tous les nodes étaient représentés mais en voulant ajouter ces objets je m'aperçois que l'appli traite un sous-ensemble.

PS : désolé de poser des questions ici, s'il y a un endroit plus approprié, dis le moi

**Comment by DoFabien** [comment]
Je parlais de l'ortho photo de l'IGN, celle par défaut dans OSM Go, avec laquelle on peut contribuer a OSM. Pour les autres fonds IGN -carte IGN, bdtopo, etc- , ce n'est pas possible (légalement parlant).

Toutes les clés ne sont pas disponibles, c'est volontaire. Quand je parle de clé, je fais référence aux "clés primaire" ( shop, amenity, etc). C'était pour éviter de surcharger l'affichage, notamment avec les voiries ou l'occupation des sols qui ne peuvent pas être mis à jour avec Osm Go qui est vraiment penser pour ajouter des POI qui sont autour de nous. Le reste, c'est beaucoup plus simple et rapide d'utiliser ID ou JOSM avec une photo aérienne, d'autant  plus que ça ne bouge pas beaucoup contrairement aux commerces .... 

La clé "barrier" pourrait être ajouter mais le problème c'est que c'est soit du linéaire, soit du ponctuel qui doit être sur le réseau de voirie pour vraiment être utile (eg calculateur d'itinéraire) 

Le" information=guidepost" est en fait un "preset" "information" de la "clé principale" "tourism=information"
https://wiki.openstreetmap.org/wiki/FR:Tag:information%3Dguidepost
Avec les différentes valeurs : https://taginfo.openstreetmap.org/keys/information#values

On peut toujours ajouter un preset manuellement, mais c'est pour l'instant fastidieux et ce serait en effet intéressant de l'ajouter.

**Comment by kroko83** [comment]
OK OK je comprends mieux.
Je n'ai pas testé l'ajout d'un preset manuel dont tu parles. Mais je ne pense pas l'utiliser car (en reprenant l'exemple des barrières) vu que la carte ne charge pas ces objets à l'écran, on risque de créer un doublon.
En tout cas, c'est déjà une très bonne appli pour contribuer ponctuellement sur des petits manques qu'on détecte autour de nous.
