### ISSUE TITLE
Modifications non effacées après envoi

### ISSUE THREAD

**Issue by JVillafruela** [DoFabien/OsmGo#19]
Tout d'abord merci pour cette appli que j'utilise régulièrement. Je suis tombé sur un comportement bizarre :
- j'ai fait des modifs qui comportaient une suppression de POI. Lors de l'envoi j'ai eu un message m'informant que le POI avait déjà été supprimé. Les autres modifs ont bien été prises en compte  (changeset [72062091](https://www.openstreetmap.org/changeset/72062091)).
- lorsque je reviens dans l'écran d'envoi les modifs sont toujours présentes. Lorsque je veux les supprimer le clic sur le bouton "confirmer" dans le dialogue d'annulation n'a aucun effet (le dialogue reste affiché).

Environnement : OSM Go! 0.9.2 - Android 9. Le problème subsiste après la mise à jour en 0.9.3.

Je peux regarder les logs / fichiers temporaires s'ils sont accessibles par le partage de fichier Android / PC.

**Comment by DoFabien** [comment]
Bonjour, et merci pour le retour.
Cette issue ressemble étrangement à la #16.
J'ai essayé de reproduire ce comportement sur l'api osm de dev, mais rien n'y a fait. 

Toutes les modifications sont restées sur l’écran d'envoi des données ? Ou seulement celle qui n'est pas passée ? (la suppression )
Quel était le type de POI supprimé ? faisait-t-il parti d'une relation ? 

Actuellement je suis en vacances jusqu'en septembre, je ne peux donc pas trop investiguer...
Pour débugger, on peut passer par l'inspecteur de chrome avec le téléphone en mode debogage et connecté en usb :
chrome://inspect/#devices
Il y aura sans doute une erreur dans la console...

**Comment by JVillafruela** [comment]
J'ai activé le débogage USB sur le téléphone, je le vois bien dans Chrome mais je ne vois pas l'appli. 

J'ai débloqué la situation en supprimant les données de l'app dans les paramètres Android.
