### ISSUE TITLE
French as language

### ISSUE THREAD

**Issue by ValorNaram** [DoFabien/OsmGo#20]
Hey,

You use french for your documentation of your app. But your app supports both english and french while the english one is incomplete. It's considered to be good practise to internationalize github projects. It is also helpful for you so you can find more contributors. It is easier than just relying fully on french speaking contributors.

A person from the Telegram OSM Germany said that "OsmGo" has potenzial but is in its current state not recommendable.

**So you see that there's interest in your project even from non-french speakers.**

**Comment by Hedaja** [comment]
I'm the guy from the German Telegram group :P
I think your app has a lot of potential. After the initial translation of the documentation into English you will find lots of people willing to translate the interface to their local language and help out with the programming.

**Comment by ValorNaram** [comment]
Since you're doing something for the OpenStreetMap Community you will find contributors there. There are various telegram groups to ask like https://t.me/openstreetmaporg and https://t.me/openstreetmapdev

Also a post in the forum to introduce your project wouldn't hurt :)

See also issue #13

**Comment by DoFabien** [comment]
Hello,
Sorry for my late response ... I was disconnected during the last month.
You're right, I'll try to find some time next week to translate the project into English.

If you want to help translate the interface into German, you can do it here:
https://osmgo.dogeo.fr/admin/#/

It is not a finalized version, but it can already be operational.
I started with "yes" and "no" but I'm not sure ... :s
You can also correct bad english translations ...;)

Thank you for your interest !

**Comment by HyknuF** [comment]
Hi, I found this issue, because I am also thinking very positive about this app. I just slightly corrected a few things in the german and english translation (UI).

So, just to to do nothing wrong:  Tag-translation: Every tag in the "DE" tags section hast to be translated right?

For example: 
Now: "Bakery" 
After: "Bäckerei" 

Am I right?

I will see if I can to a little translation work for the tags as well.

**Comment by HyknuF** [comment]
One more thing: There are two Regions for Germany "DE" and "GER". Which one has to go with? (I suggest to delete the other one?)

Kind Regards

**Comment by DoFabien** [comment]
Hi,
Thank you very much for your contribution.

That's it, you're not mistaken. 
One file per language / country.
You can see an for fr-FR [here](https://github.com/DoFabien/OsmGo/tree/master/src/assets/i18n/fr/FR) or [en-GB](https://github.com/DoFabien/OsmGo/tree/master/src/assets/i18n/en/GB).

Maybe you can start the translation directly on the file ? The interface is not very useful, especially for presets...

**Comment by ValorNaram** [comment]
> There are two Regions for Germany "DE" and "GER". 

Take "GER". Created "de" by mistake because the interface did not work correctly for me.

**Comment by ValorNaram** [comment]
> Maybe you can start the translation directly on the file ? The interface is not very useful, especially for presets...

It's useless for preset editing. I also recommend editing files directly. It's easier for linux users. Windows users I don't know. I actually thing the most people are using linux excluding the Mainstream and including communities.

**Comment by HyknuF** [comment]
"Maybe you can start the translation directly on the file ? The interface is not very useful, especially for presets...'


Yes, I will have a look to it. Since I never worked with json files etc. before, could you give me a quick advice? Thanks!

**Comment by ValorNaram** [comment]
Yes of course. The string between the quotes are the English description of the key on the left side. Also in quotes. The keys are often written in cryptic and do not contain whitespaces. They have `_` instead of whitespaces. They are also often written in uppercases. Strings you need to translate are written in normal human-readable language.

**Comment by ValorNaram** [comment]
E.g. Translate `"lbl": "Poster Box"` to `"lbl": "Postkasten"` (german)

**Comment by Binnette** [comment]
I close the issue french is supported in OsmGo! 1.5.0
