### ISSUE TITLE
Incomplete EN translation

### ISSUE THREAD

**Issue by kudlav** [DoFabien/OsmGo#22]
Great job! But few missing:

1. Node last updated time: *Updated il y a 8 minutes*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/modal/components/READ_Meta.component.ts#L24
![Screenshot_20190805-195820_Osm Go!](https://user-images.githubusercontent.com/11516259/62491539-88edad80-b7cc-11e9-8b6f-f0e909c9e0ed.jpg)
---
2. Node last updated by: *Moi même*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/modal/components/READ_Meta.component.ts#L26
How to fix:
use `Moi même` -> ``{{ MODAL_SELECTED_ITEM.META_MYSELF | translate}}``
---
3. Preset listing - *LISTE*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/assets/i18n/en.json#L93
How to fix:
`"PRIMARY_TAG_LIST": "Liste",` -> `"PRIMARY_TAG_LIST": "List",`
---
4. Preset listing - *Tous les tags*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/modal/modal.primaryTag/modal.primaryTag.html#L17
How to fix:
`Tous les tags` -> use `{{ MODAL_SELECTED_ITEM.PRIMARY_TAG_FULL | translate}}`
---
5. Preset listing - *Favoris*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/modal/modal.primaryTag/modal.primaryTag.html#L16
How to fix:
`Favoris` -> use `{{ MODAL_SELECTED_ITEM.PRIMARY_TAG_BOOKMARKS | translate}}`
![Screenshot_20190805-222759_Osm Go!](https://user-images.githubusercontent.com/11516259/62493086-82613500-b7d0-11e9-81ad-f257bd069092.jpg)
---
6. Preset custom - *Séléctionner une catégorie*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/modal/modal.primaryTag/modal.primaryTag.html#L70
How to fix:
`Séléctionner une catégorie` -> use `{{ MODAL_SELECTED_ITEM.PRIMARY_TAG_SEARCH_SELECT | translate}}`
![Screenshot_20190805-215231_Osm Go!](https://user-images.githubusercontent.com/11516259/62493431-614d1400-b7d1-11e9-846a-539f08a6d207.jpg)
---
7. Send data - *Sortie avec Osm Go!*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/services/config.service.ts#L46
---
8. Open app toast: *Charger les données de l'emprise*
https://github.com/DoFabien/OsmGo/blob/d60e1743706e2e91ba17cfe35804a78c565c4942/src/app/components/main/main.ts#L242
---
9. Splash screen: *Cartographiez les tous !*
https://github.com/DoFabien/OsmGo/blob/master/resources/splash.png
https://github.com/DoFabien/OsmGo/tree/master/resources/android/splash
### Device info:
App version: 0.9.3 Build: 903
Android: 9
Device model: SM-A405F

**Comment by DoFabien** [comment]
Thank you very much for these beautiful issues !

**Comment by kudlav** [comment]
Hi, thanks for the 0.9.4 (904) update, but the following strings are still not translated:
6. Preset custom - Séléctionner une catégorie
7. Send data - Sortie avec Osm Go!
