### ISSUE TITLE
Language in the Title of Changesets

### ISSUE THREAD

**Issue by lintux** [DoFabien/OsmGo#25]
Hi,
Recently I spotted the first changeset generated by the app. Unfortunately the title is in French, while I would recommend English in non French speaking countries.
https://www.openstreetmap.org/changeset/73905138

BR
tux67

**Comment by DoFabien** [comment]
Hi,
"Sortie avec osm go!" is a default value for changeset title. 
You can change this title before send data to OSM, the new title will be saved for the next time. 

With lastest version, the default value is an empty string. 
Thank you for your interest
