### ISSUE TITLE
Osm Go! inconnu sur hdyc

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#26]
Salut, 

Tout d'abord merci pour cette application qui permet d'ajouter simplement et efficacement les POI. 

Je regardais l'outil [hdyc](http://www.hdyc.neis-one.org/?bmaggi) qui permet de voir un résumé des changements effectués sur openstreetmap et il semble qu'Osm Go! ne soit pas reconnu comme éditeur:
La deuxième ligne de "used editor/programm" indique unknown alors que c'est bien Osm Go!

Les changements semblent bien créés avec le bon tag 
```
<tag k="created_by" v="Osm Go! 0.9.4"/>
```
Par exemple : [Osm Go!](https://www.openstreetmap.org/changeset/74036787)
Par ailleurs le tag est bien similaire à [StreetComplete](https://www.openstreetmap.org/changeset/74048522) qui remonte correctement. 

Du coup je sais pas trop d'où peut venir le problème. 

Encore merci pour cette super app !

**Comment by DoFabien** [comment]
Bonjour,
Merci pour ton intérêt. 

J'avais en effet déjà remarqué cela...
Je pense que cela vient du fait que hdyc doit avoir une liste des éditeurs d'osm les plus connus et qu'Osm Go n'en fait pas (encore?) parti.
Je n'ai pas trouvé les sourcse de "How did you contribute to OpenStreetMap", peut être faudrait-il directement écrire à la personne qui la gère.

**Comment by bmaggi** [comment]
Salut,

Pour info j'avais écrit un mail au dev de hdyc, il vient de me répondre  qu'OsmGo venait d'être ajouté à la liste. Il est possible que ça prenne un peu de temps pour se répercuter dans le service.

/Benoît
