### ISSUE TITLE
Wiki improvements

### ISSUE THREAD

**Issue by ValorNaram** [DoFabien/OsmGo#27]
Hey @DoFabien,

I translated the wiki from french into english and also updated the pictures to the recent version installed on my mobile device

Download the zip and incorporate my changes into the wiki or even better create a `docs` folder inside your repository's root and put it inside of it.

[wiki-translation-into-english.zip](https://github.com/DoFabien/OsmGo/files/3609406/wiki-translation-into-english.zip)

**Comment by DoFabien** [comment]
Hi, thanks a lot.
I pushed your files in wiki section. 

Do you think it's a good idea to incorporate it into the docs folder? It's a documentation for the users, not for developers.

**Comment by ValorNaram** [comment]
Look into the repository settings, there you will find GitHub Pages you can easily activate for your repo. Then you're free to put everything of documentation in your `docs` folder. Documentation for devs **and** users both.
