### ISSUE TITLE
main menu can't be closed once opened

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#28]
### steps to reproduce
1. open the app
2. open the main menu
3. try to close the menu
-> menu stays can't be closed. A restart is needed to close it.

### phone information
* Xiaomi Redmi Note 5
* Android 9

### app information
happens on version 0.10.0 and 0.11.0

### further information
I can't replicate the issue on version 0.10.2 and 0.11.0 using a Huawei Mate 20 Pro with Android 9.

**Comment by DoFabien** [comment]
Thank you. 
I have a Xiaomi Redmi Note 7 on Android 9 and I don't have this issue.

If you swipe left or if you click outside , the menu doesn't close?
If you stay clicked on the back-arrow (at the top right of the menu), do you have an  [ripple effect ](https://material-components.github.io/material-components-web-catalog/#/component/ripple)?

Can you test this issue on the PWA version on [https:osmgo.dogeo.fr](https:osmgo.dogeo.fr) ?

**Comment by m-rey** [comment]
Exactly, it doesn't close.
The ripple effect shows up.

The PWA version doesn't have this issue. Both Firefox nightly (Android) and Chrome (Android) are able to open and close the menu.

**Comment by ValorNaram** [comment]
I have this issue too. I use a Huawei p9 lite but I tested it also on Desktop and both don't work. I think it's a bug in ionic.

### I clicked two times. It behaves differently on the first click:
The log says `TypeError: animation.effect is undefined` when I click the back icon or swipe. The function `closeMenu()` in file `/src/app/components/menu/menu.ts` at line `87` gets not triggered.

### I click the second time (It behaves differently):
The log does not spam an error or warning when I click the back icon or swipe. The function `closeMenu()` in file `/src/app/components/menu/menu.ts` at line `87` **gets triggered** but then `this.menuCtrl.close()` does not do its job. It is a bug in the ionic framework?

All other upfollowing clicks or swipes behave in the same way like the second click.

**Comment by ValorNaram** [comment]
### Another possibility why it could not work
The code `this.menuCtrl.close();` at line `89` in file `/src/app/components/menu/menu.ts` triggers also an animation and this animation does not work so the menu cannot close.
