### ISSUE TITLE
Feature Request: Use OAuth to login

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#29]
From a security point of view, it would be very good for the application to use [OAuth](https://wiki.openstreetmap.org/wiki/OAuth) to connect to OpenStreetMap.
That way, users wouldn't have to share their OSM password with the app anymore.

**Comment by DoFabien** [comment]
Hey, 
Yes you are right, this it's at top of my todo list.
I'm trying to start this task by this weekend

**Comment by DoFabien** [comment]
My conclusion : It is impossible in a webview.
But we can use Oauth on PWA version ( osmgo.com)

**Comment by joelsgp** [comment]
Using the app gave me the impression it was still storing the password itself as plaintext, has this feature not reached me yet or should the tooltip be update?
Version 1.5.0 on android from the play store
