### ISSUE TITLE
Disponibilité sur FDroid

### ISSUE THREAD

**Issue by TeXitoi** [DoFabien/OsmGo#3]
Il serait pratique d'avoir accès à OSM Go via le store FDroid https://f-droid.org/en/

Ça donnerait également de la visibilité au projet.

**Comment by GilBr** [comment]
👍

**Comment by DoFabien** [comment]
Malheureusement il semble impossible pour l'instant de publier une application hybride (cordova) sur F-droid. 
Je regarderais plus en détail à partir du mois de septembre.

**Comment by Rudloff** [comment]
Bonjour,
(Je suis contributeur F-Droid et disponible pour répondre s'il y a des questions.)
Il est tout à fait possible de publier une application Cordova sur F-Droid, c'est juste que c'est beaucoup plus simple pour nous si le projet Android généré par Cordova (`platforms/android/` généralement) est inclus dans le dépôt Git.

**Comment by IzzySoft** [comment]
@Rudloff is there an RFP/MR for this already? Or who would open it?

@DoFabien until it reaches the official repo, I've [listed it in mine](https://apt.izzysoft.de/fdroid/index/apk/fr.dogeo.osmgo). As long as you keep tagging and attaching the APK to its corresponding tag, updates should be grabbed automatically within 24h and made available via my repo.

**Comment by IzzySoft** [comment]
@DoFabien I just got an alert from my updater that the latest version added a bunch of trackers / proprietary libs, namely: Firebase, Firebase Analytics and GMS. Is that really necessary? That way it won't ever reach the official repo, as those are not accepted (as @Rudloff will confirm). And for working with OSM, people strongly prefer to stick with open source. I was thinking to give your app a try for myself – but with that stuff inside, I definitely won't.

So could you please remove those libraries again – or at least offer a flavor (and APK) that comes without those? Thanks in advance!

Meanwhile I'll have to add 3 AntiFeatures to your app's listing in my repo: NonFreeDep (GSM), NonFreeNet (Firebase) and Tracking (Firebase Analytics) – or must remove the latest version and stop auto-updating until fixed. I did the former for now but am not sure whether I should rather think about the latter, as this certainly opposes the idea of *free* software.

**Comment by DoFabien** [comment]
Hello,
Thank you for your issue,This is not voluntary.
The process to generate the application has changed whith [Capacitor](https://capacitor.ionicframework.com/).  This probably comes from Android studio, I don't know yet

I could not watch before Sunday night, sorry

**Comment by IzzySoft** [comment]
Thanks for responding that fast, Fabien – and especially good to hear it wasn't intentional. So there's hope it will be gone with the next release – and I'll then simply drop this one and remove the AntiFeatures. :crossed_fingers:

**Comment by IzzySoft** [comment]
Just calling in to confirm the issue is solved: today my updater alerted me to remove unnecessary AntiFeatures, and I've just done so. Changes will be visible after the next sync (tomorrow). Thanks a lot!

**Comment by DoFabien** [comment]
:+1:  Thanks to you !

**Comment by tuxayo** [comment]
So for now it's only in @IzzySoft 's repo right?
I didn't find a ticket to track it's inclusion in F-Droid's official repo, is there any?
