### ISSUE TITLE
Feature Request: Add survey:date key to nodes

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#30]
The key [`survey:date`](https://wiki.openstreetmap.org/wiki/Key:survey:date) adds the possibility of mentioning, when the feature was last surveyed. This could help a lot in combination with the already implemented "show icon on old objects" option. It would help with keeping the map up to date. 

It could be recommended to the user when adding/editing a node and even be prepolulated with the current date for ease of use, similar to the way the `bicycle_parking` has the `type` key already filled in.

**Comment by DoFabien** [comment]
You can already to add that with the green button at the bottom right (not in editing mode)
Do you want to add/replace this key for every adding/editing ?

**Comment by m-rey** [comment]
I haven't noticed that, thanks for pointing it out.
It would be nice to have it as an option on every node, instead of only old ones, so users can freely use it when they see fit.

**Comment by DoFabien** [comment]
In the new release, the survey:date is added by default for each update or new object.
You can disable this in settings
