### ISSUE TITLE
Entries with errors can't be removed from upload screen

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#35]
Entries with errors aren't removed in upload screen when pressing the delete button.

## how to reproduce
1. Edit a node in OsmGo
2. Edit the same node using another program and upload the change (to bump the node version number)
3. Try to upload the change made in step 1 using OsmGo. A version mismatch error will appear. This is how it should be. 
4. Try deleting the change made on OsmGo using the delete button of the upload screen.
-> the change doesn't disappear

## device information
tested using a Xiaomi Redmi Note 5 with Android 9

## further information
* Step 1 to 3 are simply a way of creating an error and can be replaced by other steps with similar results.
* happens both in the OsmGo 0.11.1 app and PWA

**Comment by m-rey** [comment]
I've now tried clearing the changes using the "delete all application cache", without success.
Nothing visibly changed, as the edits are still there, the application is still logged in, the icons are still being displayed, etc.
Tested on both the PWA and normal application.

**Comment by DoFabien** [comment]
Hi, 
Thank you for this good issue!
It looks like #19 but I've never been able to reproduce this.
By following your instructions, I have an error but I still can delete the changes.

So I fixed this error, I think that's your problem too.
Can you test the PWA app with this fix ? You have to wait a few minutes (sec?) for the changes to be downloaded, then you need to restart the app. 
It should be version 11.0.2

Thank you !

PS: After  "delete all application cache", you need to kill and restart the app

**Comment by JVillafruela** [comment]
I experienced the same behavior this afternoon 

![Screenshot_1-error](https://user-images.githubusercontent.com/3534219/65447364-aa672f00-de36-11e9-8e29-1e2bad0f0518.jpg)

Resulting changeset : https://www.openstreetmap.org/changeset/74814772 
When sending again 

![Screenshot_2-send-after-error](https://user-images.githubusercontent.com/3534219/65447490-f023f780-de36-11e9-9688-ae6ef1d81597.jpg)

The faulty node is the IBIS hotel. All other nodes have been sent in changeset #74814772. The"delete" button has no effect (after confirmation the changes do not disappear) .

**Comment by DoFabien** [comment]
Thank you,
I hope that the new version will fix this bug (0.11.2) .. If it's not the case, please reopen this issue

**Comment by JVillafruela** [comment]
Fix works for me. Tested with v0.11.2 :

- Added yesterday a node amenity=toilets in OSM Go! Changeset [75243171](https://www.openstreetmap.org/changeset/75243171)
- Added today wheelchair=yes on this [node](https://www.openstreetmap.org/node/6848063448) with josm 
- Added same info in OSM Go! + other changes => changeset [75274652](https://www.openstreetmap.org/changeset/75274652). The toilets node is in error.
- When I went back in the upload screen I've deleted the node in error with the "delete" button

**Comment by DoFabien** [comment]
Thank you ! 
The next release of the app will bring big changes... 
Good by Codova, hello PWA with only browser APIs (geolocation, device orientation and vibration)
PWA has a lot of advantages for Osm Go! (fastest, lighter, update only some files in the background, caching tiles, etc )

I already integrated the Oauth login ( it was impossible with the cordova sandbox...)
I also code a new openstreetmap data converter that runs entirely in the background (in a webworker)
I plan to push this update ( a [TWA](https://developers.google.com/web/updates/2019/02/using-twa)) on the play store during the next week.
You can already install  and test this latest PWA on [https://osmgo.dogeo.fr](https://osmgo.dogeo.fr) 
Your returns are welcome.

PS : @JVillafruela with this version, you can switch from the OSM **prod** server to the OSM **dev** server. (Convenient to find bugs)
To activate the "developer mode", go to About page and tap 5 times on version card.  Now you can switch to the osm dev  server in setting page (at the bottom) .
The OSM dev: http://api06.dev.openstreetmap.org
You must create an account for this server.
