### ISSUE TITLE
Map not displayed with Brave Browser

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#39]
Hi,

I installed the latest version on Android 1.0.1 and the map isn't visible when I start the map. 
When switching my default browser from [Brave](https://play.google.com/store/apps/details?id=com.brave.browser&hl=en) to Chrome, it works perfectly.
* Is there a way to make the app working with brave ? 
* Is there a way to specify the browser used by Osm Go (without changing the default one) ? 

With Chrome the map looks a lot better :) 
Thank you for this awesome app.

Some other questions/remarks: 
 * Is there a release note ? I didn't found it. 
* Also no sure if this google store version is meaningful since it doesn't exist in [github release](https://github.com/DoFabien/OsmGo/releases) )
* Do you prefer bug/question in english or french ?

**Comment by DoFabien** [comment]
Hi,
It seems that there are many problems with this new version ... Too much change at once ... and especially the transition to [TWA](https://developers.google.com/web/updates/2019/02/using-twa)
I restore the old version on the Play Store but it will not be maintained anymore ...

The application migrates to "[PWA](https://en.wikipedia.org/wiki/Progressive_web_applications) ". 
It's faster, lighter, the cache can be used even for the basemaps, updates can be made in the background with just the elements that have been changed, etc ... And available on all platforms in the form of a web page.
This version is available on **[osmgo.com](https://osmgo.com)**
Once installed, I think Chrome has the priority to open the PWA. Can you confirm this ?

You can check the realease note [here](https://github.com/DoFabien/OsmGo/blob/develop/CHANGELOG.md), you were too fast ;)

My English is pretty bad, but other people can understand ...

**Comment by bmaggi** [comment]
I confirm that the app on Android is back to the previous version.

Not sure how PWA in Android handle the browser, basic tests seems to confirm that the default browser (configured in Andoird settings) is used to open the PWA. 

I can confirm that accessing  https://osmgo.com/#/main from Brave on Android has the same problem (empty map).

More elements:
* I tried to change the brave configuration but no way to remove the problem
* The site is displaying the map perfectly on my _computer_ (tried :  **Brave**, Chrome, Firefox)

**Comment by DoFabien** [comment]
It's too early for the TWA, we return to the classic app for a few more years ...
