### ISSUE TITLE
1er test - Quelques remarques

### ISSUE THREAD

**Issue by GilBr** [DoFabien/OsmGo#4]
Je viens de tester la version 0.3.0 sur une Asus Zenfone Zoom (Android 5.0).
Et le 1er contact est très satisfaisant. ça fonctionne bien, c'est intuitif, fluidde et compatible pour les utilisateurs de base et plus confirmé. Bravo !

J'ai quelques remarques sur l'utilisation : 
- C'est dommage d'être obligé d'activer la Géolocalisation pour utiliser l'appli (dans mon cas, si je choisis d'annuler l'activation, cela reste ensuite bloqué sur l'écran Geolocation)
- La flèche de localisation s'affole un peu dans mon cas, si on bouge la direction n'est pas correctement indiquée, voire la flèche tourne sur elle même
- Il a une coquille sur l'écran de sauvegarde => Enoyer au lieu de Envoyer (aussi sur la diapo ;-)

Je vais continuer à tester (pour l'instant dans le bus).

**Comment by DoFabien** [comment]
Bonjour et merci ! 
J'ai apporté quelques modifications. Si on refuse la géolocalisation, la carte s'ouvre sur la France, il faudra donc zoomer sur la zone qui nous intéresse  à la main... Ca peut être un peu fastidieux...
Si l'on a pas refusé l'autorisation de la geoloc mais que l'app ne reçoit pas de coordonnées dans les 6 secondes, un bouton s'affiche pour bypasser cette page.
df28b82d2c588e827a5b59af373abf1254e83403 

En ce qui concerne l'orientation un peu extravagante, j'ai fait quelques mises à jour, il y a du mieux mais c'est pas encore tout a fait ça... de99c0cfe894c8db5ab37b7d8ab62bb780de8bea
J'ai encore deux trois choses à corriger et je publie ça ce week end.
