### ISSUE TITLE
Please install Chrome Stable 72

### ISSUE THREAD

**Issue by adolfintel** [DoFabien/OsmGo#41]
Why?
If the app uses a WebView, you need to check the version of that system component, not Google Chrome.

**Comment by DoFabien** [comment]
I did a rollback from the 1.0.0 to 0.12.2.
Future versions will no longer be with a webview, Cordova ... It will be Progressive Web Applications and maybe in TWA on the playstore.
That's the reason.

You can go to this PWA at [osmgo.com](osmgo.com)

**Comment by DoFabien** [comment]
... It's too early for TWA or PWA only... 
I will keep both versions in parallel (webview and PWA)
