### ISSUE TITLE
Small feature : display/translate recycling:clothes

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#42]
When editing a container (amenity=recycling) some recycling:* are nicely displayed

Example 👍 
recycling:paper               -> Papier 
recycling:plastic              -> Plastique
recycling:glass_bottles   -> Bouteilles de verre et bocaux
recycling:clothes             -> recycling:clothes

I tried to use the [admin ui](https://admin.osmgo.com/#/tags/fr/FR) to change 
I believe that I changed it as I now see 

> recycling:clothes | Vêtements

in the presets.

But it is still not displayed on my smartphone. 
Did I missed something ? Is there a certain validation or time to wait ?

**Comment by bmaggi** [comment]
Thanks, I confirm that it works on the website.

**Comment by DoFabien** [comment]
Live on 0.12.2
