### ISSUE TITLE
Map not displayed in Android app after update to v0.12.0

### ISSUE THREAD

**Issue by JVillafruela** [DoFabien/OsmGo#43]
After updating the Android application to v 0.12.0 today :

- the OSM map is not displayed anymore (note that I had no data from previous run). I've tried to clear the app cache (in the menu) but it didn't work.
- the aerial imagery is correctly displayed. 
- when I access the pwa app on the same device (Nokia7+ / Android 9 / Firefox mobile) the  map is correctly displayed.
- the app works, I can load, update the osm objects and send the data back to OSM.

**Comment by DoFabien** [comment]
Hello,
Thank you. 
This has been fixed in version 0.12.2
The problem came from glyph that I had deleted, thinking them unused ... But no, oups

**Comment by JVillafruela** [comment]
It works now, thanks Fabien.
