### ISSUE TITLE
Apply last map position and zoom level when restarting app

### ISSUE THREAD

**Issue by chris-est** [DoFabien/OsmGo#45]
Hi, i have a feature request:

When i close the app and later re-open it, the map position and zoom is reset and is always showing France.
Can the app save the position and zoom level to where i made my last changes and re-apply this when the app is re-opened?

**Comment by DoFabien** [comment]
Hi, yes you are right.
It is not very complicated, I will integrate it in the next version, probably next week. 
Thank you for this idea

**Comment by chris-est** [comment]
Thanks! I am looking forward to it :+1: 

Btw: Is there a setting to disable GPS by default? OsmGo could try GPS as soon as i tap on the bottom right button?

**Comment by Binnette** [comment]
I close this issue. Here is the behavior is OsmGo 1.5.0:

- if GPS is enabled, on startup OsmGo will zoom on user location
- if GPS is disabled, on startup OsmGo will reopen last location with last zoom
