### ISSUE TITLE
PWA OAuth isn't working

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#47]
The OAuth login gets stuck on https://osmgo.com/assets/land.html?oauth_token=xxxxxxxxxxxxxxx

## device information
Xiaomi Redmi Note 5, Android 9

## how to reproduce
0. delete cache and data of Chrome (Android). Alternatively, delete all application data using the option in the settings.
1. open the menu and press login. You are redirected to OpenStreetMap
2. log in OpenStreetMap. You are redirected to an OpenStreetMap website to authorize the OsmGo! application
3. Give the OsmGo! application permission to access your data.
You'll then be redirected to a [blank page](https://i.imgur.com/DryIlaG.png) with the URL https://osmgo.com/assets/land.html?oauth_token=xxxxxxxxxxxxxxx
You don't get redirected back to the OsmGo! application.
If you then go to https://osmgo.com manually, you are still not logged in.

**Comment by DoFabien** [comment]
Hi, 
I just identified the problem. 
It happens when we try to connect from the browser (osmgo.com) while the PWA is installed on the desktop. It automatically opens the PWA, with an other scope...

If you uninstall the PWA (osmgo (PWA)) it will works.
If you open the PWA from the des it works.

Do you confirm that?

**Comment by m-rey** [comment]
I sadly can't confirm that your steps work.

I've removed the PWA app (and the normal one) from my phone.
I've also removed all cache and data of Google Chrome (including site storage).
Then, I've tried using OsmGo (https://osmgo.com) from the Google Chrome browser, but it still doesn't work.

**Comment by m-rey** [comment]
PWA OAuth works in the new release.
