### ISSUE TITLE
Preset

### ISSUE THREAD

**Issue by nlehuby** [DoFabien/OsmGo#5]
**English version:**
Is it possible to use h2geo format to store presets: https://github.com/jawg/h2geo-presets ?

It will allow us to reuse in OsmGo thematic presets created in other apps without the need to redifine the presets in OsmGo.

**Original version:**
Est-ce qu'il serait possible d'intégrer le format h2geo pour les presets : https://github.com/jawg/h2geo-presets ?

Ça permettrait de réutiliser dans OsmGo les presets thématiques déjà créés par ailleurs sans avoir à refaire le travail.

**Comment by ValorNaram** [comment]
@DoFabien It might be possible for you to use the [presets iD uses](https://github.com/openstreetmap/iD/tree/2.x/data/presets) so you solve the problem of outdated ones. Specified ones for a specified country can exists in parallel like

- General source of presets applying for all countries
  - https://github.com/openstreetmap/iD/tree/2.x/data/presets
- Plus the specified ones for a country e.g. Great Britain, France, Germany
  - They overwrite the ones from the general source

File structure

    Presets-general
      amenities
      leisures
      healthcare
      ...
    Presets-country-specified
      Great Britain
        public transport
        healthcare
        ...
      France
        public transport
        healthcare
        ...
      Germany
        infrastructure
        healthcare
        ...
     ...

**Comment by DoFabien** [comment]
Hi,
You are right and I'm working on it.
But there will be some differences with iD presets... 

In Osm go "tags" = "presets" in iD
In Osm go "presets" = "fields" in iD
... I know, it is not very logical, but it would require a lot of changes in the code...

You can see these big files [here](https://github.com/DoFabien/OsmGo/tree/feature/RefactoringTags/src/assets/tags%26presets) : 
and changelog [here](https://github.com/DoFabien/OsmGo/blob/feature/RefactoringTags/CHANGELOG.md#100) 
## future structure
#### Tag example (eg preset in iD) 
```json
{
      "icon": "mi-library", 
      "markerColor": "#EF9228",
      "presets": [
        "wheelchair",
        "phone",
        "website"
      ],
      "lbl": {
        "en": "Library",
        "de": "Bibliothek"
      },
      "terms": {
        "en": "book",
        "de": "Bibliothek, Bücherei"
      },
      "description": {
        "en": "A place to read and/or lend books",
        "de": "Eine Bibliothek"
      },
      "geometry": ["point", "area"],
      "tags": {"amenity": "library"},
      "moreFields": [
        "access_simple",
        "air_conditioning",
        "email",
        "fax",
      ],
      "id": "amenity/library",
      "excludeCountryCodes": ["FR"]
    }
```

#### Presets example (eg fields in iD) 
```json
"school:FR": {
        "key": "school:FR",
        "countryCodes": ["FR"],
        "type": "select",
        "lbl": {"fr": "Ecole FR", "en": "school:FR"},
        "options": [
          {
            "v": "maternelle",
            "lbl": {
              "fr": "Maternelle (petite à grande section)",
              "en": "maternelle"
            }
          },
          {
            "v": "primaire",
            "lbl": {"fr": "Primaire (maternelle et élémentaire)", "en": "primaire"}
          },
          {
            "v": "élémentaire",
            "lbl": {"fr": "Élémentaire (CP à CM2)", "en": "élémentaire"}
          },
          {"v": "collège", "lbl": {"fr": "Collège (6e à 3e)", "en": "collège"}},
          {"v": "lycée", "lbl": {"fr": "Lycée (2nde à Terminale)", "en": "lycée"}},
          {
            "v": "secondaire",
            "lbl": {"fr": "Secondaire (collège et lycée)", "en": "secondaire"}
          }
        ]
      },
```
This is a draft version... I think it will be ready in January

**Comment by Binnette** [comment]
I close this issue as for now Osm Go! v1.5.0 use iD presets.
Feel free to open it again (or open another one) if this issue is not completely addressed 👍
