### ISSUE TITLE
Unable to login after update to v0.12.4

### ISSUE THREAD

**Issue by JVillafruela** [DoFabien/OsmGo#50]
After updating today the app to v0.12.4 (from Google play) I'm unable to login : 
- I click on the login button in the app
- I'm redirected to https://www.openstreetmap.org/oauth/authorize?oauth_callback=http%3A%2F%2Flocalhost%2Fassets%2Fland.html&oauth_token=xxxxxxxxxxxx on my mobile browser (firefox 68.2.1 / android 9.0)
- after I grant the authorization I'm redirected to http://localhost/assets/land.html?oauth_token=yyyyyy 
- I'm not logged in the app

**Comment by DoFabien** [comment]
Oups... I released the wrong version...
I fix this blunder.
Thank you !

**Comment by JVillafruela** [comment]
Updated the app this morning, it works now :-)
