### ISSUE TITLE
Hide Some elements

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#53]
A nice feature would be to allow filtering/hiding of some elements (and forbid to create these elements)

Some time the map is filled with elements that may not interest the user.

I would be happy to hide:
* Tree
* Swimming pool
* Highway crossing

**Comment by m-rey** [comment]
If anything, the user should be able to decide what to hide.
Arbitrarily deciding what elements to hide is not helpful at all.

I, for example, like to add trees to OSM, among other things.

Also, you want to have the possibility of updating the survey date of elements, including trees, swimming pools and highway crossings. Hiding those elements would result in users not checking and thus not updating the survey date. This may result in stale data.

All in all, filtering options would be a nice addition. But the filter definitely needs to be customizable by the user, in my opinion.

**Comment by m-rey** [comment]
I also don't understand why the creation of filtered elements should be forbidden.
Can't the element just not be created in the first place instead of actively forbidding its creation?
I don't see any value in restricting node creation based on filters.

**Comment by bmaggi** [comment]
Obviously the filter list should be customizable per user. (We all have different point of interest ;) )

I think blocking the creation of filtered elements can prevent some double creation. 

For example, if I hide the swimming pool, but at some point want to add one (while forgetting, that it's in the filtering list), it will create a double.

**Comment by DoFabien** [comment]
Creating filters can be very dangerous and can lead to the creation of duplicates.

Sometime, one element can be tagged with differentes keys. If you hide "office=travel_agent", 
you can very easily create a duplicate with "shop=travel_agency".

I will try to implement this quickly, but use with caution

**Comment by m-rey** [comment]
I agree. Maybe a reminder on the node creation page could be added to tell the user that some nodes are being filtered and thus are not visible. This could help prevent duplicate node creation.

**Comment by bmaggi** [comment]
The functionality is available since 1.0.0.

Works fine for me in 1.1.0 :)
