### ISSUE TITLE
Load data arrow animation is only played once

### ISSUE THREAD

**Issue by m-rey** [DoFabien/OsmGo#56]
When pressing the arrow in the bottom left part of the main view to load data, the rotating arrow animation is only showed once. (It turns 360° and then stops.)

## what I expected to happen
It thought it would rotate as long as it is still loading/processing the data, because the button is also being disabled (indicated by a lower opacity) during that time.

**Comment by DoFabien** [comment]
Thank you Martin,
This bug will be fixed in the next BIG release,  maybe next week, I hope...

**Comment by m-rey** [comment]
Indeed, this is fixed in the new release. Thank you!
