### ISSUE TITLE
Brand preset

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#57]
It might be useful to add a brand preset on some elements, for example real_estate and hostel.
(A similar brand preset as the one present for banks)

I can add the Brand preset in real estate using 
https://admin.osmgo.com/
with a list element, I can configure a new preset with a fixed list of brands.

I saw that brands are proposed (probably selected from POI already present) 

Can I add this preset ? Will it impact only me or everyone ?

**Comment by DoFabien** [comment]
Hi,
In the next version, we will use [name-suggestion-index](https://github.com/osmlab/name-suggestion-index/)
Don't use admin.osmgo.com... the structure of data has changed... :s
I still need to test the new version, but I think the release will arrive in the next few days.
If you want to test it, you are welcome :)

You can also contibute to name-suggestion-index, it will impact on all users of Osm Go or iD !

**Comment by bmaggi** [comment]
I close the issue since in 1.1.0, brand preset are present for Hostel and office=estate_agent

I will have a look to name-suggestion-index
