### ISSUE TITLE
Utilisation sur le web ?

### ISSUE THREAD

**Issue by nlehuby** [DoFabien/OsmGo#6]
Il semble que `ionic` permet de créer aussi des webapp type PWA.

Est-ce qu'on peut s'envisager une version web d'OsmGo ?

**Comment by DoFabien** [comment]
Une version web est bien sur possible, les applications hybrides utilise le webview des smartphones. Par contre on perd les fonctionnalités liés à Cordova qui permet d'utiliser les fonctionnalités natives de l'OS (accès aux fichiers, à la base sqlite, orientation, gps, etc...). Il ne reste donc plus que les fonctions supportées le navigateur lui même.
Dans notre, cas ce qui peut être limitant c'est l'accès au stockage. Avec Cordova on peu accéder à une base Sqlite qui permet de stocker autant de données que l'on souhaite. Coté navigateur natif, on utilise le localStorage  qui lui est limité à quelques dizaines(?) de Mo ce qui interdira donc la mise en cache des fonds carto pour une potentielle utilisation hors ligne par exemple.

Une version [web est disponible ici](https://osmgo.dogeo.fr/www/).

**Comment by nlehuby** [comment]
Merci ! même si c'est un mode dégradé, je trouve que ça reste utilisable donc que c'est intéressant à proposer.

**Comment by Binnette** [comment]
L'url https://osmgo.dogeo.fr/www/ n'est plus valide. Je propose de simplement clore ce bug.
