### ISSUE TITLE
1.0.0 not working on Android ?

### ISSUE THREAD

**Issue by bmaggi** [DoFabien/OsmGo#61]
The latest version is not working on my Pixel 3 XL
 
I got the buttons but an empty grey map with all this configurations:
* using Chrome on https://osmgo.com/#/main
* using Firefox on https://osmgo.com/#/main
* using Brave on https://osmgo.com/#/main
* using the App installed by the Google Store
* using the PWA version

It works on my computer, so my guess is that there is a bad configuration somewhere.

Is there an easy way to extract some logs to identify the issue ?

**Comment by DoFabien** [comment]
Thank you, 
I think the problem comes from the high resolution of the screen.
Can you give me your "Resolution (dppx)" of "density" section from here : 
[mydevice.io](https://www.mydevice.io/)

**Comment by bmaggi** [comment]
Here is the full density section:
* Resolution (dpi) 336.00dpi
* Resolution (dppx) 3.50dppx
* Resolution (dpcm) 132.28dpcm

**Comment by DoFabien** [comment]
I had misunderstood the concept of pixelratio of mapbox...
It should be better with the new version 1.1.0.

Can you close this issue if it works,
Thank you !

**Comment by bmaggi** [comment]
It's working thx
