### ISSUE TITLE
butcher + kosher

### ISSUE THREAD

**Issue by patman37** [DoFabien/OsmGo#62]
Bonjour, 
Merci pour cette app très utile  et ergoniomique. j'ai rencontré un petit problème avec les tags.
pour créer une boucherie Kascher je cherche _butcher_ et ensuite je précise Speciality : _kosher_
cela donne:
- butcher=kosher
- shop=butcher

selon le wiki de OSM (https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dbutcher)
il faudrait:
- diet:kosher=yes
- shop=butcher

Je ne sais si c'est un problème avec l'app ou avec des presets.
cordialement

**Comment by DoFabien** [comment]
Bonjour,
Oui c'était bien une erreur dans les presets.
Je viens de la  corriger dans la nouvelle version (1.2.0)
Merci !
