### ISSUE TITLE
Feature request: widget for filling hours (opening, collection, etc.)

### ISSUE THREAD

**Issue by maroneze** [DoFabien/OsmGo#63]
I really like the ease of use of the interface of OSM Go!, and I've been using it much more often than StreetComplete. The only thing that makes me come back to StreetComplete from time to time is the fact that I keep forgetting the exact syntax to fill in opening hours (and collection times, etc).

I'd just like to add a feature request related to it. Here are a few examples of how some Android apps do it.

StreetComplete has a widget for filling in opening hours (https://github.com/westnordost/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours) that is very helpful, with a few templates (weekdays with lunch break, every day, etc.).

![streetcomplete-opening-hours](https://user-images.githubusercontent.com/3179395/81529521-4b234400-935f-11ea-9bf2-416d440841c0.png)

Vespucci has a different widget (https://github.com/MarcusWolschon/osmeditor4android/blob/9c337df70ae6fc8dede08df40f7f0f5944163e8d/src/main/java/de/blau/android/propertyeditor/tagform/OpeningHoursDialogRow.java) that is arguably more powerful, but also maybe more complex to use.

![vespucci-opening-hours](https://user-images.githubusercontent.com/3179395/81529556-62623180-935f-11ea-9bac-17bfe0b4fab3.png)

In the end, maybe a simple link to the [opening hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours) page in the OSM wiki, as a reminder of the syntax, could be helpful.

**Comment by bmaggi** [comment]
I agree with this suggestion :). In fact most of the time : I create the POI with osm go and add opening hours with street complete. 

It would be very useful to have such widget.

**Comment by DoFabien** [comment]
Better late than never.
I implemented an interface for viewing and read/create/modify  "opening_hours" (only for intervals, not for collection times...)
This is a first version, it only allows you to read/modify/add simple "opening_hours" format (without specific days, weeks or holidays).
The rest may come later

It use a part of [YoHours](https://framagit.org/PanierAvide/YoHours) by Adrien Pavie

Example : 

![opening hours](https://user-images.githubusercontent.com/10403759/98104136-54b4e100-1e96-11eb-8309-829a908ace40.gif)

**Comment by maroneze** [comment]
That's great! Thanks a lot! Hope to try it soon (too bad that "Contribute to public community mapping efforts" is not one of the allowed exceptions in the French lockdown :grin:)!
