### ISSUE TITLE
emergency=fire_hydrant preset needs improvement

### ISSUE THREAD

**Issue by momu** [DoFabien/OsmGo#65]
I recently stumbled upon a lot of fire hydrants which are tagged with `fire_hydrant:type=pond`. According to https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant `pond` does not exist. Most probably the people mean:

```
emergency=fire_hydrant 
fire_hydrant:type=pipe
fire_hydrant:pressure=suction
water_source=pond
```

Please rework the preset according to the approved tagging scheme.

**Comment by DoFabien** [comment]
Thank you,
The presets for "emergency = fire_hydrant" are now the same as the iD presets.
