### ISSUE TITLE
Restaurant as self service laundry

### ISSUE THREAD

**Issue by kudlav** [DoFabien/OsmGo#66]
OsmGo! marks self-service restaurant with delivery as laundry.

Didn't edited anything with OsmGo, it's fresh install.
The node:
https://www.openstreetmap.org/node/7799001334

Language: cs_CZ
Platform: Android 10 (Google Play)

![Screenshot_20200809-235615_Osm Go!](https://user-images.githubusercontent.com/11516259/89742667-0ad97c00-da9c-11ea-8e18-8be6f6da72ed.png)

**Comment by DoFabien** [comment]
Hello and thank you.
I just fixed this bug, thanks
