### ISSUE TITLE
Email preset not displayed

### ISSUE THREAD

**Issue by bagage** [DoFabien/OsmGo#68]
When trying to add a new POI (like fast food), email preset is not displayed while it seems handled in code.

However if you edit a POI with an existing email, it is displayed with a `<>` icon and no translation:

![image](https://user-images.githubusercontent.com/1451988/91889101-92766d00-ec8d-11ea-9121-1632c7179a28.png)

**Comment by DoFabien** [comment]
Hello, 
This was a normal behavior, because the "email" field did not appear in the "fastfood" preset.
But now, if the field's key is identical to a preset's ID, it will take it .

I need to test it a little more before putting it into production.
Probably this weekend

**Comment by Binnette** [comment]
I can not reproduce this bug on version 1.5.0.
