### ISSUE TITLE
Enable autocomplete on name

### ISSUE THREAD

**Issue by bagage** [DoFabien/OsmGo#69]
It seems autocomplete is disabled on name input. However most of brands are actual name and having some autocomplete would be great. 

It might be true for other presets as well, but in general I'm not sure what's the benefit of disabling autocomplete? Disabling autocorrect should be enough, isn't it?

**Comment by Binnette** [comment]
A solution was implemented, but I don't knwo how to test it. I close the issue for now. Feel free to open a new one and provide more description, screenshot and so on.
