### ISSUE TITLE
[Bug] Effacement du nom du POI après modification des tags

### ISSUE THREAD

**Issue by GilBr** [DoFabien/OsmGo#7]
Avec la version 0.5.0 (Build 500) nous avons constaté avec un collègue nantais que l'édition d'un POI faisait disparaitre le nom du POI s'il est déjà renseigné. 
- Cela survient si l'on modifie la valeur d'un tag ou si on ajoute un tag + la valeur. 
- Le nom disparait après validation de la modification avec le bouton vert

Nous l'avons constaté sur 2 smartphones différents après la dernière mise à jour.

**Comment by DoFabien** [comment]
La 0.5.3 devrait être la bonne !
