### ISSUE TITLE
Login issues 

### ISSUE THREAD

**Issue by tdyoma** [DoFabien/OsmGo#70]
Hi. I can't login in the app with 100% correct credentials.

Pixel 3, Android 11
![Screenshot_20201003-104445](https://user-images.githubusercontent.com/12847116/94986254-e82c8680-0565-11eb-9643-25e2253a6c6d.png)

**Comment by tdyoma** [comment]
And I can't see the 0auth authorization in the app
![Screenshot_20201003-105514](https://user-images.githubusercontent.com/12847116/94986396-178fc300-0567-11eb-98c0-bb1b003fc81f.png)

**Comment by zeriss** [comment]
Same problem on One Plus 5T on android 9 for 1 day.

**Comment by Binnette** [comment]
A solution have been implemented plus I can't  reproduce the issue.
