### ISSUE TITLE
Add Basque as translatable language

### ISSUE THREAD

**Issue by Porrumentzio** [DoFabien/OsmGo#71]
Currently it's not in the web for translating the app

**Comment by Binnette** [comment]
Basque have been added as the available languages. Stay tune for the "localization". We are currently setting up POEditor.

**Comment by Binnette** [comment]
Hi @Porrumentzio, you can now translate Osm Go! to basque. Follow the instructions here: https://github.com/DoFabien/OsmGo/blob/develop/CONTRIBUTING.md#translate
