### ISSUE TITLE
Traduction de la page wiki "FR:Osm_Go!" en français...

### ISSUE THREAD

**Issue by u4y0u** [DoFabien/OsmGo#73]
... à corriger/compléter si besoin. ;-)

le nouveau lien: [ici](https://wiki.openstreetmap.org/wiki/FR:Osm_Go!
![FR-OSM_Go!](https://user-images.githubusercontent.com/54479065/103458203-0c833500-4d06-11eb-95cd-0d3b9db76da0.png)
)

**Comment by u4y0u** [comment]
page annexe :
[Template](https://wiki.openstreetmap.org/wiki/Template:User_Osm_Go!/doc)
utilisant :
[File](https://wiki.openstreetmap.org/wiki/File:Osm_Go!.png)

**Comment by Binnette** [comment]
Thanks @u4y0u
