### ISSUE TITLE
Bouton de vérification

### ISSUE THREAD

**Issue by Kalepom** [DoFabien/OsmGo#8]
Bonjour, 

Je rencontre des soucis avec le bouton de vérification. La plupart du temps, un appui long dessus n'a pas d'effet. Étonnamment ça fonctionne très bien de temps en temps sur un objet, puis plus d'effet sur les suivants que je souhaite vérifier.

**Comment by DoFabien** [comment]
Bonjour,
Je n'oublie pas cette issue, je m'en occuperais à partir de la première semaine de novembre, j'aurais plus de temps.

**Comment by DoFabien** [comment]
Le lonpress buggait bel est bien ...  du coup c'est devenu un simple bouton avec une confirmation afin d'éviter les fausses saisies.
