### ISSUE TITLE
App name different than documentation

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#83]
The documentation on Google Play says it is called OSM Go.
However the title of the app itself is Mapping less frustrating.

**Comment by DoFabien** [comment]
Where did you find the title "Mapping less frustrating" ?
I only find it in the "README.md" as subtitle

**Comment by jidanni** [comment]
$ w3m -dump https://play.google.com/store/apps/details?id=fr.dogeo.osmgo | egrep -i frust\\|osm.*go
```
Mapping less frustrating!
A short user documentation can be found here : https://dofabien.github.io/OsmGo
```
![20220123T031413](https://user-images.githubusercontent.com/1230959/150652525-e0e7ec57-028d-4ac3-8e73-d6b82d46474e.jpg)

**Comment by timothywashere** [comment]
Yeah, it appears as the main name of the app in my google play store too. Android 11

**Comment by Binnette** [comment]
App name have been fixed in PlayStore 👍️
