### ISSUE TITLE
Say typing just a username would work too

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#90]
I typed a username instead of my email address and it worked. Therefore the prompt should say both are okay

**Comment by Binnette** [comment]
Hi @jidanni. It has been fixed on develop branch:

![image](https://user-images.githubusercontent.com/6597721/175766167-d5b6a519-4a41-4183-9e67-6c0237e3ab6a.png)


Feel free to make any comments/suggestions 😇👍️
