### ISSUE TITLE
Don't say "view on GitHub"

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#91]
We are told the docu mentation is on https://dofabien.github.io/OsmGo/ .

However when we get there we see a big _view on GitHub_ banner message.

However we will eventually just end up where we started because that is the place the documentation is.

So maybe just have a link that says GitHub Home. Don't say View on GitHub.

**Comment by Binnette** [comment]
Issue fixed in 19a8680b87027024903e4301ca87d9135d2d814b
