### ISSUE TITLE
Allow placing a POI at a given exact x y

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#98]
All editing apps should have the ability to put a point at a certain x y. For instance we know there is a monument at exactly 24.11111,120.22222.
Well, there should be a way for us to place it exactly there.
Yes, not only the ability to fly to a given x y. But also be able to place an item at a given x y without having to move around the map with our fingers.

**Comment by matkoniecz** [comment]
It is dubious whether such functionality is worth extra clutter in the interface.

If you know exact coordinates already then benefit from mapping on mobile device is tiny

**Comment by DoFabien** [comment]
Yes, I agree with @matkoniecz
