### ISSUE TITLE
Show imagery brand name in the corner

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#99]
Okay, apparently I have selected the Bing imagery.

Well on the map there should be a Bing logo to assure me that's indeed what I selected. And also to comply with Bing's copyright.

**Comment by matkoniecz** [comment]
>  And also to comply with Bing's copyright.

Where it is stated as required?

**Comment by Binnette** [comment]
Should address #111 first

**Comment by jidanni** [comment]
> > And also to comply with Bing's copyright.
> 
> Where it is stated as required?

https://www.google.com./search?q=bing+maps+attribution+terms has some guesses.

**Comment by Binnette** [comment]
Fixed in 652ef0a5f8950d26b7e9676a5d1540d67db7e7b0 but we have to work on it. Some copyright do not appears corretly depending on the layer.
